Feature/file encoding
jplag/JPlag pull request #1026
Opened 2023-04-12 10:51 UTC by TwoOfTwelve

fixes #746

Uses https://unicode-org.github.io/icu/userguide/conversion/detection.html to detect the file encoding.

2023-04-13 15:37 UTC, Kr0nox approved these changes
Looks good to me

2023-04-18 20:20 UTC, dfuchss requested changes
Code looks good to me. Just some minor remarks

2023-04-18 20:20 UTC, dfuchss commented on language-api/src/main/java/de/jplag/util/FileUtils.java
> +    private static final Charset defaultOutputCharset = StandardCharsets.UTF_8;
Constants should be named like this ..
```suggestion
    private static final Charset DEFAULT_OUTPUT_CHARSET = StandardCharsets.UTF_8;
```

2023-04-18 20:20 UTC, dfuchss commented on language-api/src/main/java/de/jplag/util/FileUtils.java
> +        });
I'd suggest not using lambdas here (esp. lambda blocks). Simply use normal for loops. that could increase readability :)

2023-04-18 20:20 UTC, dfuchss commented on language-api/src/main/java/de/jplag/util/FileUtils.java
> +        AtomicReference<Double> mostProbableConfidence = new AtomicReference<>((double) 0);
```suggestion
        AtomicReference<Double> mostProbableConfidence = new AtomicReference<>(0.0);
```

2023-04-21 08:14 UTC, tsaglam requested changes
Just one small thing.

2023-04-21 08:14 UTC, tsaglam commented on language-api/src/main/java/de/jplag/util/FileUtils.java
> +            if (reader.read() != '\uFEFF') {
Use constants here.

2023-04-25 18:17 UTC, tsaglam approved these changes

2023-04-25 20:19 UTC, dfuchss approved these changes
Just one minor suggestion

2023-04-25 20:19 UTC, dfuchss commented on language-api/src/main/java/de/jplag/util/FileUtils.java
> +    private static final char BOM = '\uFEFF';
```suggestion
    private static final char BYTE_ORDER_MARK = '\uFEFF';
```

2023-04-26 13:20 UTC, merged