Feature/refactor cpp2 language module
jplag/JPlag pull request #1167
Opened 2023-07-04 09:46 UTC by TwoOfTwelve

This PR refactors the cpp2 tests and language module.
Also contains minor improvements for the abstract antlr utils and test utils.

The refactoring of the cpp2 module fixes a couple of issues with the module. As far as I can tell all tokens are still extracted by the same rules, although it would be nice if someone could verify that.

The fixed errors are:
-Nested if-else statements lead to the wrong line being assigned to the second else token
-The Antlr grammar was missing DivAssign in the list of operators for operator overloading

The things changed in the testutils:
-The tokenprinter is now called for the tests (should we maybe only do this if the test fails?)
-The configured tests are now passed as a list instead of a set internally, so the order of tests does not change between runs.

2023-07-04 10:16 UTC, mbrdl commented
With this change, how could I add semantic information to the tokens as is done in the [TokenGeneratingTreeScanner](https://github.com/jplag/JPlag/blob/develop/languages/java/src/main/java/de/jplag/java/TokenGeneratingTreeScanner.java)? How could I track variables, for instance?

2023-07-05 05:55 UTC, tsaglam commented
@TwoOfTwelve could you extend the PR description a bit? List the fixes to the cpp2 language explicitly (e.g., which tokens/syntax elements were affected).

Also, for testing the token extraction quickly, you can always use the token printer to print the token before and after your change with a large cpp file and then to a text diff.

Finally, the expansion for semantic token information would be of highest priority right now.

2023-07-05 05:56 UTC, tsaglam commented
@TwoOfTwelve could you extend the PR description a bit? List the fixes to the cpp2 language explicitly (e.g., which tokens/syntax elements were affected).

Also, for testing the token extraction quickly, you can always use the token printer to print the token before and after your change with a large cpp file and then to a text diff.

Finally, the expansion for semantic token information would be of the highest priority right now.

2023-07-05 05:56 UTC, tsaglam commented
@TwoOfTwelve could you extend the PR description a bit? List the fixes to the cpp2 language explicitly (e.g., which tokens/syntax elements were affected).

Also, for testing the token extraction quickly, you can always use the token printer to print the token before and after your change with a large cpp file and then to a text diff.

Finally, the expansion for semantic token information would be of the highest priority right now.

2023-07-05 10:00 UTC, tsaglam requested changes
We may need to clarify in the language readme that this grammar has been changed compared to the original one. Ideally, add a note on what has been changed.

2023-07-05 10:00 UTC, tsaglam commented on languages/cpp2/src/main/java/de/jplag/cpp2/CPPListener.java
> +public class CPPListener extends AbstractAntlrListener {
Javadoc

2023-07-05 10:00 UTC, tsaglam commented on languages/cpp2/src/main/java/de/jplag/cpp2/CPPListener.java
> +     * @param collector The token collector
This would be a case of JavaDoc trivial! :D

2023-07-05 10:00 UTC, tsaglam commented on languages/cpp2/src/test/java/de/jplag/cpp2/CppLanguageTest.java
> +public class CppLanguageTest extends LanguageModuleTest {
Javadoc, what is tested? At which granularity? few sentences can provide outsiders clarity here!

2023-07-05 10:00 UTC, tsaglam commented on languages/cpp2/src/main/antlr4/de/jplag/cpp2/grammar/CPP14Parser.g4
> +	| DivAssign
Maybe add a comment here that this was changed from the original grammar. You could also make a PR to the antlr repo.

2023-07-06 15:32 UTC, mbrdl requested changes
some minor things

2023-07-06 15:32 UTC, mbrdl commented on language-antlr-utils/src/main/java/de/jplag/antlr/AbstractAntlrListener.java
> +            ParserRuleContext next = currentcontext.getParent();
`currentContext = currentContext.getParent()` would be simpler

2023-07-10 12:42 UTC, mbrdl commented on languages/cpp2/src/main/java/de/jplag/cpp2/CPPListener.java
> +        createStartStopMapping(ClassSpecifierContext.class, UNION_BEGIN, UNION_END, rule -> rule.classHead().Union() != null);
Right, makes sense. Do you have time to make this PR? Otherwise I can do it as well. But I should really get started on the semantic token info 😅

2023-07-10 13:49 UTC, merged