Added the option to initialize the parser lazily for AbstractAntlrLan…
jplag/JPlag pull request #1222
Opened 2023-08-05 18:37 UTC by TwoOfTwelve

For language-antlr-utils - AbstractAntlrLanguage:
Added the option to initialize the parser later in a separate method, to allow passing more data to the parser. To do that, you need to implement the initializeParser method and pass nothing to the super constructor.

2023-08-07 10:26 UTC, Kr0nox requested changes

2023-08-07 10:26 UTC, Kr0nox commented on language-antlr-utils/src/main/java/de/jplag/antlr/AbstractAntlrLanguage.java
> +    protected AbstractAntlrParserAdapter<?> initializeParser() {
Maybe there shoudl also be a doc comment here about it needing to be implemented when using the empty constructor and it not being needed when using the other one

2023-08-09 12:50 UTC, Kr0nox approved these changes

2023-08-10 11:26 UTC, tsaglam approved these changes

2023-08-10 11:26 UTC, merged