Java 21
jplag/JPlag pull request #1370
Opened 2023-11-05 12:13 UTC by TwoOfTwelve

To update java for java 21 the following things have to be done:
- [x] Update java version in pom.xml
- [x] Update java version in workflow files
- [x] Update expected java version for tests
- [x] Verify the old tests are still working
- [x] Write rules and tests for new java features
- [x] Verify the rules below indeed do not impact jplag
- [x] Enable Previews
- [x] Right now the java version for enabling previews is hard coded. It should be unified with the version in NewJavaFeaturesTest

The following new features are relevant to jplag:
- [x] Record Patterns and Pattern matching for switch have been finalized
    Works without changes
- [x] String templates (preview)
    Works without changes
- [x] Unnamed patterns and variables (preview)
    Ignore vardefs without name (javac maps "_" to an empty string)
- [x] Anonymous classes. Produced negative positions for end of class tokens
- [x] Guards for cases. Should be extracted as an additional if.

The following changes should not impact jplag:
- [x] Virtual threads / Structured concurrency
- [x] Foreign function api (preview) [maybe poses problems for obfuscation of plagiarisms]
- [x] Scoped values

2023-11-18 10:08 UTC, SirYwell commented
There are a few things that aren't really covered:

- case pattern with guards (`case Integer i when i > 0:`)
  - it might make sense to desugar it into an `if`
- [JEP 445](https://openjdk.org/jeps/445) (though it might make sense to skip that, there are a few changes to how the compiler handles it in Java 22)

Is that intentional?

2023-11-20 19:50 UTC, SirYwell commented on languages/java/src/main/java/de/jplag/java/TokenGeneratingTreeScanner.java
> +            addToken(JavaTokenType.J_IF_BEGIN, positions.getEndPosition(ast, node), 0, CodeSemantics.createControl());
This should be `END` I guess?

2023-11-27 13:45 UTC, tsaglam approved these changes

2023-11-28 08:10 UTC, Kr0nox requested changes
Just one small thing

2023-11-28 08:35 UTC, tsaglam commented on languages/java/src/main/java/de/jplag/java/TokenGeneratingTreeScanner.java
> +        if (!node.getName().contentEquals("")) {
Good call, I think we even talked about that before!

2023-11-28 08:38 UTC, Kr0nox approved these changes

2023-11-28 15:56 UTC, merged

2023-12-01 09:41 UTC, dfuchss commented
-> https://github.com/jplag/JPlag/actions/runs/7057421814/workflow#L54

Missed one last line :)