Printable report viewer
jplag/JPlag pull request #1409
Opened 2023-11-30 17:16 UTC by Kr0nox

This PR makes the report viewer printable. (closes #754)

The overview and cluster view print without the table, due to its items being loaded dynamically by a library.

In the comparison view the the list at the top gets replaced by a table containing the line numbers

2024-01-12 15:44 UTC, sebinside requested changes
Thank you for making this primarily a CSS solution. I played with this PR using Edge and Chrome together with different printers and PDF export, and I noticed quite some whitespace and also cut off code parts (see the attached screenshot). While the former harms the planet, the latter could also make the solution unusable, especially regarding legal stuff. Please have another look at the solution (and also resolve the merge conflicts). Other than this, the solution is good, thank you!

![image](https://github.com/jplag/JPlag/assets/7331248/73be045d-a32a-42f8-b66c-05874875943d)

2024-01-15 15:21 UTC, Kr0nox commented
I could not reproduce the cutoff with any browser. What browser and version did you experience this with?

Regarding the whitespace: Most of it is either spaced by the browser, when you have specific amounts of matches or because the otherwise diagramms wont be cut off

2024-01-16 11:49 UTC, sebinside commented
I had this problem in the following browsers:
* Edge Version 120.0.2210.133
* Chrome Version 120.0.6099.217
* Firefox 121.0.1 (here, even more things broke in the print view)

Let's discuss this in our next meeting.

2024-01-22 08:15 UTC, sebinside approved these changes

2024-01-22 08:15 UTC, merged