ImmediatlyWriteZip
jplag/JPlag pull request #1416
Opened 2023-12-05 13:46 UTC by TwoOfTwelve

Changed the report object factory to immediately write to a zip file instead of creating single files.

I tried to check how the runtime changed, by running jplag over 100 copies of the jplag code.
This is the result:

old:
8:10.19
7224.86s user 29.80s system

new:
7:46.55
6893.25s user 28.17s system

The majority of the time however was spent on comparing the submissions, so this might not be representative.

I build an artificial "worst-case" scenario to check the speed and both the old and the new version took the same time.

2023-12-07 09:37 UTC, tsaglam commented
As discussed, let's test how the performance is changed for a larger data set and include it in the PR description.

2023-12-13 09:30 UTC, tsaglam requested changes

2023-12-13 09:30 UTC, tsaglam commented on cli/src/main/java/de/jplag/cli/CLI.java
> +                ReportObjectFactory reportObjectFactory = new ReportObjectFactory(new File(cli.getResultFolder() + ".zip"));
Why is ".zip" hardcoded here? I think this should be part of the factory and probably a constant.

2023-12-13 09:30 UTC, tsaglam commented on core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
> +    public ComparisonReportWriter(Function<Submission, String> submissionToIdFunction, JPlagResultWriter jPlagResultWriter) {
better name it resultWriter

2023-12-13 09:30 UTC, tsaglam commented on core/src/test/java/de/jplag/reporting/reportobject/ReportObjectFactoryTest.java
> +        try (RandomAccessFile raf = new RandomAccessFile(file, "r")) {
Name it `file` or similar to avoid abbreviations.

2023-12-13 09:30 UTC, tsaglam commented on core/src/test/java/de/jplag/reporting/reportobject/ReportObjectFactoryTest.java
> +            // handle if you like
Shouldn't this be a test failure?

2023-12-13 09:30 UTC, tsaglam commented on core/src/test/java/de/jplag/special/ReadmeCodeExampleTest.java
> +            ReportObjectFactory reportObjectFactory = new ReportObjectFactory(new File("/path/to/output"));
This test is meant to remind us that we need to adapt the readme if we change the basic usage of JPlag!

2023-12-14 17:22 UTC, Kr0nox commented
What is the wanted behaviour, if jplag cant write the zip (can for example be forced by having a zip with the same name open).
Previously then you would still have the folder with the files. As I understand it, this will not happen now and the results are lost?

2023-12-15 07:59 UTC, Kr0nox commented on core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
> +        for (JPlagComparison comparison : comparisons) {
I would suggest also performing a test with a lot of very small submissions (1000 maybe?, but each only a few small files), to see whether removing the parralelism actually decreased performance here

2024-01-25 12:47 UTC, tsaglam approved these changes

2024-01-25 12:48 UTC, tsaglam commented
@TwoOfTwelve we have one conflict here.

2024-02-02 08:30 UTC, tsaglam requested changes
@TwoOfTwelve can you resolve the conflicts so I can merge?

2024-02-02 09:58 UTC, tsaglam approved these changes

2024-02-02 10:33 UTC, merged