Implemented progress bars for the cli
jplag/JPlag pull request #1433
Opened 2023-12-12 14:20 UTC by TwoOfTwelve

Simplifies the logging output and add progress bars.

![recording](https://github.com/jplag/JPlag/assets/101133883/c12ab8e4-050e-4fde-9f6d-cfed137b0aa0)

The progress bars are implemented the following way:

The core module contains the infrastructure for progress bars. This includes interfaces for creating and manipulating progress bars (logging/ProgressBar and logging/ProgressBarProvider). It also contains some static code (logging/ProgressBarLogger), that allows the core to create new progress bars and the ui to set a new ProgressBarProvider in order to decide how the progress bars are implemented. The core module also has a dummy implementation for the interfaces, that simply writes to the log.

The CLI has been added implementations for the interfaces, that internally call a progress bar library (https://github.com/ctongfei/progressbar).

This way of implementing it, might behave strangely if JPlag is called multiple times simultaneously from the same JVM, but as this feature is currently only meant for the cli, I think the risk of that happening is negligible.

2023-12-13 08:42 UTC, tsaglam commented
@TwoOfTwelve can you add an example of the new log to the PR description?

2023-12-13 08:53 UTC, tsaglam reviewed
Had a discussion with @dfuchss, here is some early feedback.

2023-12-13 08:53 UTC, tsaglam commented on core/src/main/java/de/jplag/UiHooks.java
> +public interface UiHooks {
Probably better named `ProgressListener`.

2023-12-13 08:53 UTC, tsaglam commented on core/src/main/java/de/jplag/UiHooks.java
> +    UiHooks NullUiHooks = new UiHooks() {
Implicitly static final, so must be upper case with underscores.

2023-12-13 08:53 UTC, tsaglam commented on cli/src/main/java/de/jplag/cli/CliUiHooks.java
> +public class CliUiHooks implements UiHooks {
Probably better named `ProgressBarListener`.

2023-12-13 08:53 UTC, tsaglam commented on core/src/main/java/de/jplag/UiHooks.java
> +    }
Better put this into its own file.

2023-12-13 08:53 UTC, tsaglam commented on core/src/main/java/de/jplag/JPlag.java
>      public JPlag(JPlagOptions options) {
Should stay deprecated to tie the object creation to the run call. Just introduce a new run method that overloads the existing one.

2023-12-13 08:53 UTC, tsaglam commented on core/src/main/java/de/jplag/JPlag.java
> +    public JPlag(JPlagOptions options, UiHooks uiHooks) {
As this constructor is new, it can be private.

2023-12-13 08:53 UTC, tsaglam commented on core/src/main/java/de/jplag/JPlag.java
> +    public JPlagResult run() throws ExitException {
Should stay static, this would be a major API-breaking change.

2024-01-25 12:50 UTC, tsaglam commented
@TwoOfTwelve we still have some comments from the last review here.

2024-02-02 08:39 UTC, tsaglam requested changes
The new classes are lacking documentation, thus making it harder to review this PR.
Please provide JavaDoc comments. Also: The design rationale of the interfaces in the core and the implementations in the CLI, as well as the separation between the provider and the progress bar, could be discussed in the PR description. Ideally, PR descriptions not only explain the feature and its importance but also how it was realized.

2024-02-02 08:39 UTC, tsaglam commented on core/src/main/java/de/jplag/strategy/ParallelComparisonStrategy.java
> +            progressBar.step();
Is there a reason this is done here and not in the compareSubmissions method? This ties the logging to the parallel strategy and makes the code a bit more cluttered.

2024-02-02 13:33 UTC, tsaglam commented on core/src/main/java/de/jplag/strategy/ParallelComparisonStrategy.java
> +            progressBar.step();
As the progress bar behaves like a logger, I would create it in `AbstractComparisonStrategy` and store it as a (private) field. I would then call `progressBar.step()`  after the GST in  `AbstractComparisonStrategy.compareSubmissions()`. The advantage would be, that the concrete strategy never needs to bother with the progress bar. You can even get rid of the the calculation if you create the progress bar in the `buildComparisonTuples()` method.

2024-02-08 09:29 UTC, tsaglam requested changes
Just a few minor issues. The solution regarding logging and the parallel strategy looks good!

2024-02-08 13:58 UTC, olmokramer commented
@TwoOfTwelve I'm sorry for the long delay, I've finally got some time to take a look at this PR. It looks like this will suit our needs of getting the progress. We would need to implement our own progress bar provider because we're running JPlag on some server and need to have the results show up in a web interface, but given the simplicity of the `ProgressBar` interface that should be no problem. Thanks for following up on this!

2024-02-09 11:58 UTC, tsaglam commented on cli/src/main/java/de/jplag/cli/logger/TongfeiProgressBarProvider.java
> +            case COMPARING -> "Comparing Submissions";
I prefer UI in core to the duplication, but I understand your design choice here.

2024-02-10 18:45 UTC, dfuchss commented on cli/src/main/java/de/jplag/cli/logger/TongfeiProgressBarProvider.java
> +            case COMPARING -> "Comparing Submissions";
I think it can stay in the CLI :)

2024-02-11 11:37 UTC, Kr0nox commented on languages/cpp2/src/main/java/de/jplag/cpp2/CPPListener.java
> +        typeSpecifierRule();
@TwoOfTwelve Did you mean to push these changes to this PR?

2024-02-19 09:06 UTC, tsaglam reviewed
Looks good! Could you take a look at the sonar issues?

2024-02-20 10:39 UTC, merged