JavaScript language module
jplag/JPlag pull request #1494
Opened 2024-01-20 20:36 UTC by Kr0nox

Adds a language module for javascript.
It just extends TypeScript, since every typescript keyword is also a javascript keyword.

I moved the js specific tests from the ts language module to the js language module

2024-01-22 09:32 UTC, Kr0nox commented
> @Kr0nox the language loader should check for language interface implementations, and thus the Javascript module should be mentioned when the dependency in the CLI module ist set...

The Language Loader currently uses the `getName` method of a Language. Currently this returns the Parser for every language. As you mentioned it should mention the javascript method, but the parser still is the typescript parser. How do you want that handled?

2024-01-22 09:46 UTC, tsaglam commented
I would say this is an internal detail that is not important for users. So it is fine when it says javascript for now...

2024-01-22 09:47 UTC, Kr0nox commented
But it gets mentioned when starting the CLI in this message
```
LanguageLoader - Available languages: '[C/C++ Scanner [basic markup], C/C++ Parser, C# 6 Parser, EMF metamodel, EMF models (dynamically created token set), Go Parser, Javac based AST plugin, Kotlin Parser, LLVMIR Parser, Python3 Parser, R Parser, Rust Language Module, Scala parser, SchemeR4RS Parser [basic markup], SCXML (Statechart XML), Swift Parser, Text Parser (naive), Typescript Parser]
 ```

2024-01-22 09:49 UTC, tsaglam commented
I think I may have misunderstood something, let's discuss it tomorrow, that is probably easier. :D

2024-01-25 14:08 UTC, tsaglam requested changes
Just one minor issue.

2024-01-25 14:08 UTC, tsaglam commented on languages/javascript/pom.xml
> +            <version>4.4.0-SNAPSHOT</version>
Use `${revision}` here, as this allows us to only change one variable to increment the version number.

2024-01-25 14:08 UTC, tsaglam commented on languages/javascript/pom.xml
> +            <version>4.4.0-SNAPSHOT</version>
Also here.

2024-01-26 10:53 UTC, tsaglam approved these changes

2024-01-26 10:54 UTC, merged