Renamed cpp to c and cpp2 to cpp
jplag/JPlag pull request #1496
Opened 2024-01-23 14:55 UTC by TwoOfTwelve

Renamed cpp to c and cpp2 to cpp as discussed.

2024-01-31 10:41 UTC, Kr0nox commented
And update the README of the now cpp (formerly cpp2) module, since it still mentions the module as cpp2

2024-02-02 08:29 UTC, tsaglam requested changes
Please also update the language table in the main readme, add a readme to c, update the cpp readme, and check if the wiki needs to be updated.

2024-02-02 08:29 UTC, tsaglam commented on report-viewer/src/model/Language.ts
> +  CPP = 'C++(C) Parser',
```suggestion
  C = 'C Scanner',
  CPP = 'C++ Parser',
```

2024-02-02 08:29 UTC, tsaglam commented on languages/c/src/main/java/de/jplag/c/CLanguage.java
> +        return "C(C++) Scanner [basic markup]";
```suggestion
        return "C Scanner";
```

2024-02-02 08:29 UTC, tsaglam commented on languages/cpp/src/main/java/de/jplag/cpp/CPPLanguage.java
> +        return "C++(C) Parser";
```suggestion
        return "C++ Parser";
```

2024-02-02 13:18 UTC, tsaglam commented
@TwoOfTwelve since sonar is back, we have a few issues here. Also don't forget my comments regarding the readme files.

2024-02-13 14:07 UTC, Kr0nox requested changes

2024-02-13 14:07 UTC, Kr0nox commented on README.md
> -  javascript
This line should not be removed

2024-02-13 14:07 UTC, Kr0nox commented on languages/cpp/README.md
> And update the README of the now cpp (formerly cpp2) module, since it still mentions the module as cpp2

2024-02-15 07:23 UTC, tsaglam approved these changes

2024-02-15 07:23 UTC, tsaglam commented
@Kr0nox ready from your side?

2024-02-15 08:31 UTC, Kr0nox approved these changes

2024-02-15 08:40 UTC, merged