Changes to MatchMerging as its tests by nils.
jplag/JPlag pull request #1550
Opened 2024-02-09 12:08 UTC by TwoOfTwelve

Contains the changes to MatchMerging by Nils. I also refactored the code in some places where my IDE suggested it.

2024-02-10 05:22 UTC, uuqjz commented
@TwoOfTwelve tag me as reviewer

2024-02-10 08:09 UTC, tsaglam commented
> @TwoOfTwelve tag me as reviewer

You can do that yourself in the top right corner... ;)

2024-02-10 08:11 UTC, uuqjz commented
@tsaglam I cant do that, it seems i am neither mainainer nor StudDev

2024-02-10 10:35 UTC, tsaglam commented
Should work now.

2024-02-10 11:16 UTC, uuqjz commented on core/src/test/java/de/jplag/merging/MergingTest.java
> +        assertTrue(matchesBefore.equals(expectedBefore) && matchesAfter.equals(expectedAfter));
Oversight of mine:
Split into two assertEquals please

2024-02-10 11:18 UTC, uuqjz requested changes
Comment above

2024-02-13 13:28 UTC, uuqjz approved these changes

2024-02-13 13:53 UTC, tsaglam approved these changes

2024-02-13 13:53 UTC, merged