Match merging: Use default values for CLI
jplag/JPlag pull request #1563
Opened 2024-02-15 12:05 UTC by uuqjz

Fixed an issue where the default values where not used for the CLI.

2024-02-15 14:55 UTC, uuqjz commented
@tsaglam Ready for Review!

2024-02-15 15:18 UTC, tsaglam requested changes
Just two minor things. Not all existing test cases fulfill this, but new ones should.

2024-02-15 15:18 UTC, tsaglam commented on cli/src/test/java/de/jplag/cli/MergingOptionsTest.java
> +public class MergingOptionsTest extends CommandLineInterfaceTest {
Add a short JDoc comment here. Along the lines of "Test cases for the options of the match merging mechanism."

2024-02-15 15:18 UTC, tsaglam commented on cli/src/test/java/de/jplag/cli/MergingOptionsTest.java
> +    @Test
Add @Description("...") here. This is what is shown in your IDE. Can be a brief sentence describing the tested behavior (test if default values are used when cresting merging options).

2024-02-16 08:27 UTC, tsaglam approved these changes

2024-02-16 08:27 UTC, merged