FilePathUtils.joinZipPathSegments error on windows
jplag/JPlag pull request #1609
Opened 2024-02-24 16:50 UTC by TwoOfTwelve

The file creation now uses the path api instead of manual concatenation. I cannot test it on windows. So it would be great if someone could confirm it also works on windows.

Fixes #1592

2024-02-24 20:19 UTC, Kr0nox commented
This does not generate the expected report with the single submission files, so just a folder with files.
Input folder:
```
Folder
└Sub1.java
└Sub2.java
```

We would expect the report zip be look like this:
```
files
 └Sub1.java (This is a folder)
 |  └ Sub1.java
 └Sub2.java (This is a folder)
 |  └ Sub2.java
Json Files
```

But the zip looks like this:
```
files
 └Sub1.java (This is a file)
 └Sub2.java (This is a file)
Json Files
```

2024-02-25 14:06 UTC, Kr0nox commented
> Also fixes https://github.com/jplag/JPlag/issues/1610

I would suggest moving this to a diferent PR, since it is very independent of the other issue

2024-02-26 13:45 UTC, Kr0nox requested changes
Except for some JDoc this looks good.

Tested on windows

2024-02-26 13:45 UTC, Kr0nox commented on core/src/main/java/de/jplag/reporting/FilePathUtil.java
> +    public static Path forceRelativePath(Path path) {
JDoc

2024-02-26 13:45 UTC, Kr0nox commented on core/src/main/java/de/jplag/reporting/FilePathUtil.java
> +    public static Path createRelativePath(String path) {
JDoc

2024-02-26 13:45 UTC, Kr0nox commented on core/src/main/java/de/jplag/reporting/FilePathUtil.java
> +    public static String pathAsZipPath(Path path) {
JDoc

2024-02-29 14:34 UTC, Kr0nox approved these changes
Tested on windows. Works with:
- [x] Single Submission Folder
- [x] Multiple Submission Folders
- [x] Single Folder of Submission Foles
- [x] Multiple Folders of submission files (appart from #1610

2024-03-11 08:35 UTC, tsaglam approved these changes

2024-03-11 08:36 UTC, merged