Avoided overwriting of files
jplag/JPlag pull request #1716
Opened 2024-04-18 10:05 UTC by TwoOfTwelve

Avoids overwriting of existing results files. Tries to find a new unique filename by adding (<number>). Aborts if the selected file is not writable. Also adds a cli option --overwrite, that ignores existing files. This still aborts if the file cannot be written.

Solved #1670

2024-04-18 16:50 UTC, tsaglam commented
@TwoOfTwelve could you add a small test for this?

2024-04-19 06:19 UTC, Kr0nox requested changes

2024-04-19 06:19 UTC, Kr0nox commented on cli/src/main/java/de/jplag/cli/CLI.java
> +        if (!(targetFile.canWrite() || (!targetFile.exists() && targetFile.getAbsoluteFile().getParentFile().canWrite()))) {
I would suggest refactoring this expression to make it a bit more readable

2024-04-19 06:19 UTC, Kr0nox commented on cli/src/main/java/de/jplag/cli/options/CliOptions.java
> +        @Option(names = "--overwrite", description = "If this option is specified and a result file already exists it will be overwritten.")
I would change this text to be more online with other flags. Meaning: Just state what it does without the `If this option is specified`

2024-05-03 10:00 UTC, tsaglam requested changes
One minor thing plus the 5 small sonar issues left todo.

2024-05-16 13:11 UTC, tsaglam approved these changes

2024-05-17 05:25 UTC, Kr0nox approved these changes

2024-05-17 08:10 UTC, merged