Added new framework for Cli-Tests
jplag/JPlag pull request #1744
Opened 2024-05-02 10:42 UTC by TwoOfTwelve

This PR contains a new framework for cli tests. With this new framework it is possible to test the new cli more intuitive and check different artifacts than the options.

2024-05-10 11:28 UTC, Kr0nox commented on cli/src/test/java/de/jplag/cli/test/CliArg.java
> +    public static CliArg<String[]> SUBMISSION_DIRECTORIES = new CliArg<>("", true);
Do we want to have every CLI arg as a constant here? Another option I could imagine working is, generating them from the https://github.com/jplag/JPlag/blob/feature/cliTests/cli/src/main/java/de/jplag/cli/options/CliOptions.java Class and then referencing them by there names in the methods were you now give a CliArg Object. 
I dont really have a preference, just wanted to leave that as an option for discussion here

2024-05-10 11:31 UTC, Kr0nox commented on cli/src/test/java/de/jplag/cli/test/CliTest.java
> +                try (MockedStatic<OutputFileGenerator> generatorMock = Mockito.mockStatic(OutputFileGenerator.class)) {
Is there a way to write this without 3 try blocks? Especially when only one of them has a catch

2024-05-10 11:36 UTC, Kr0nox commented on cli/src/test/java/de/jplag/cli/test/CliTest.java
> +    public abstract void initializeParameters(CliArgBuilder args);
Do we want to leave this abstract or make it have a default implementation where it calls `addDefaultParameters`

2024-05-10 11:37 UTC, Kr0nox commented on cli/src/test/java/de/jplag/cli/ClusteringTest.java
> +        JPlagOptions options = runCliForOptions(args -> args.with(CliArg.CLUSTER_PP_PERCENTILE, .5));
Extract `-5` into a constant, also with the assert below

2024-05-10 11:39 UTC, Kr0nox commented on cli/src/test/java/de/jplag/cli/OldNewRootDirectoriesArgumentTest.java
> +        JPlagOptions options = runCliForOptions(args -> args.with(CliArg.SUBMISSION_DIRECTORIES, new String[] {"root1", "root2"}));
Maybe also extract this array into a variable and then use its length in the assert below
Same with all other arrays in this test class

2024-05-22 07:00 UTC, tsaglam requested changes
Just a few issues and one minor sonar issue.

2024-06-06 10:11 UTC, Kr0nox requested changes

2024-06-06 10:11 UTC, Kr0nox commented on report-viewer/package-lock.json
Did you make these changes to the package-lock on purpose? running `npm i` readds the lines removed/changed. 
If this was not on purpose, please revert the changes (you can simply run `npm i` and commit that)

2024-06-19 06:38 UTC, tsaglam commented
There were still conflicts for the package lock, I resolved them by overriding with develop.

2024-06-19 11:21 UTC, tsaglam approved these changes

2024-06-19 18:22 UTC, Kr0nox approved these changes

2024-06-20 09:06 UTC, merged