Added command line option for log-level
jplag/JPlag pull request #1751
Opened 2024-05-03 12:38 UTC by TwoOfTwelve

Added a cli option to set the log-level

2024-05-04 08:04 UTC, Kr0nox commented
Do we want the progress bars on level that shows less than info? (WARN, ERROR)
Do we want to keep the progress bars on DEBUG and TRACE? They are barely visible anyway and due to #1719 the additional messages are cut off sometimes

2024-05-22 07:36 UTC, tsaglam requested changes
One small thing and a sonar issue.

2024-05-22 07:36 UTC, tsaglam commented on cli/src/main/java/de/jplag/cli/logger/JPlagLoggerBase.java
> +    public static Level currentLogLevel = LOG_LEVEL_INFO;
I would prefer to keep this private and use a static setter instead.

2024-06-13 10:45 UTC, Kr0nox requested changes
Readding my comment from above as requested changes, to not forget it before merging:
> Do we want the progress bars on level that shows less than info? (WARN, ERROR) Users that select these levels probably actually only want warnings and errors

> Do we want to keep the progress bars on DEBUG and TRACE? They are barely visible anyway and due to https://github.com/jplag/JPlag/issues/1719 the additional messages are cut off sometimes

In the meeting we decided we dont want the bar on any level other than info

2024-06-19 06:42 UTC, tsaglam commented
One conflict has to be solved before I can merge.

2024-06-20 07:54 UTC, Kr0nox approved these changes

2024-06-27 07:22 UTC, tsaglam approved these changes

2024-06-27 07:24 UTC, merged