Feature/allow single submissions
jplag/JPlag pull request #1852
Opened 2024-07-09 14:26 UTC by euberdeveloper

Ref to #1445 and #1848, fixes #1850

2024-07-09 14:28 UTC, euberdeveloper commented
It fixes also this feature request: #1849.

The code probably is to be reviewed by the maintainers and re-adjusted, but it works as a proof of concept

2024-07-10 08:26 UTC, tsaglam commented
@euberdeveloper reviews will follow. For now, please take a look at the Sonar issues and see which ones you can resolve.

2024-07-16 08:38 UTC, Kr0nox requested changes
Could you add a simple e2e case to this pr, so we can make sure, it is always correctly exported.
Here are references on where they are implemented currently:
https://github.com/jplag/JPlag/blob/develop/report-viewer/tests/e2e/OpenComparisonTest.spec.ts
https://github.com/jplag/JPlag/blob/develop/.github/workflows/complete-e2e.yml

2024-07-16 14:44 UTC, euberdeveloper commented
Ok, I will do it next week

2024-07-18 12:01 UTC, tsaglam commented
@euberdeveloper can you also extend the PR description so it becomes clearer what aspects this PR addresses and how it does so? Also how we can test it. We may need to discuss what features we want to include and which ones we don't want to include. Finally, please switch your target branch to develop, the main branch is only for releases.

2024-08-26 16:43 UTC, euberdeveloper commented
@tsaglam I've created a new branch that forks that:
* branches develop instead of master
* uses spotless to avoid style issues
* adds tests that prove that the new behaviour works and work also as an example to understand it

Please take a look at it, I think that it is a good improvement that fixes #1849 and #1848 .

For a description of what it does, you can take a look at those issues (#1849  and #1848 ), namely:
* If I want to test a single new submission against many old ones, it works instaed of throwing an error
* If I have, for example, a new submission called "submission" and an old submission called also "submission", instead of throwing an error, requiring me to manually change the names of the folders, it gets as submission name the min. different path, e.g. "submissions/submission" and "olds/submission".
* I find the old behaviour of throwing errors in those 2 cases limiting the tool and requiring users to find tricks to avoid those errors

The pull request will reference this old one, that I'm closing

2024-08-26 16:43 UTC, closed without merging