Avoid progress bar overlap
jplag/JPlag pull request #1866
Opened 2024-07-11 10:09 UTC by TwoOfTwelve

Avoids overlaps of the progress bar with log outputs by delaying the log outputs while a progress bar is being shown.

Log outputs that happen during the progress bar are instead shown below it, after it is done:
```
Loading Submissions   100% [=========================] 2/2 (0:00:00 / 0:00:00) 
Parsing Submissions     0% [                               ] 0/2 (0:00:00 / ?) line 5:12 mismatched input '=' expecting '{'
line 5:12 mismatched input '=' expecting '{'
Parsing Submissions   100% [=========================] 2/2 (0:00:00 / 0:00:00) 
2024-07-11-12:01:45_008 [WARN] Submission - Failed to parse submission test1.cs:
failed to parse 'test1.cs'class de.jplag.csharp.grammar.CSharpParser$Namespace_or_type_nameContext cannot be cast to class de.jplag.csharp.grammar.CSharpParser$Local_variable_declarationContext (de.jplag.csharp.grammar.CSharpParser$Namespace_or_type_nameContext and de.jplag.csharp.grammar.CSharpParser$Local_variable_declarationContext are in unnamed module of loader 'app')
2024-07-11-12:01:45_012 [WARN] Submission - Failed to parse submission test2.cs:
failed to parse 'test2.cs'class de.jplag.csharp.grammar.CSharpParser$Namespace_or_type_nameContext cannot be cast to class de.jplag.csharp.grammar.CSharpParser$Local_variable_declarationContext (de.jplag.csharp.grammar.CSharpParser$Namespace_or_type_nameContext and de.jplag.csharp.grammar.CSharpParser$Local_variable_declarationContext are in unnamed module of loader 'app')
```

There is still some overlap with antlr, because antlr writes directly to System.err. That problem is addressed in #1868.

2024-07-19 10:59 UTC, tsaglam requested changes
There are a few issues regarding sync and naming here. Also, please check the Sonar issues.

2024-07-19 10:59 UTC, tsaglam commented on cli/src/main/java/de/jplag/cli/logger/TerminalPrinter.java
> +public class TerminalPrinter {
`DelayablePrinter` is probably more fitting, what do you think?

2024-07-19 10:59 UTC, tsaglam commented on cli/src/main/java/de/jplag/cli/logger/TerminalPrinter.java
> +    }
I would either synchronize the whole method (draconian synchronization) or do the double-checked locking pattern here instead of synchronizing twice.

2024-07-19 10:59 UTC, tsaglam commented on cli/src/main/java/de/jplag/cli/logger/TerminalPrinter.java
> +    private boolean isDelayed;
Move those at the top with the other fields for consistency's sake.

2024-07-19 10:59 UTC, tsaglam commented on cli/src/main/java/de/jplag/cli/logger/TerminalPrinter.java
> +    public void println(String output) {
If you are synchronizing the whole method body anyways and the class is the monitor, just add `synchronized` as method keyword.

2024-07-19 10:59 UTC, tsaglam commented on cli/src/main/java/de/jplag/cli/logger/TerminalPrinter.java
> +    public void unDelay() {
I think I prefer `resume()`...

2024-07-19 11:27 UTC, tsaglam commented on cli/src/main/java/de/jplag/cli/logger/TerminalPrinter.java
> +    }
Interesting, did it give you input as to why it wants this implementation?

2024-07-19 12:50 UTC, tsaglam approved these changes

2024-07-19 14:09 UTC, Kr0nox commented
![grafik](https://github.com/user-attachments/assets/fc6d58b2-c1a6-403f-97e3-b8bea9adeaee)
Do we want the errors to be printed like they are in the screenshot or after a specific progress bar has run to 100%.
With the current way, a specific progress bar may be printed multiple times with different percentages.

2024-07-22 06:45 UTC, tsaglam commented
> Do we want the errors to be printed like they are in the screenshot or after a specific progress bar has run to 100%. With the current way, a specific progress bar may be printed multiple times with different percentages.

Both would be possible. Without the duplication, it looks cleaner. With the duplication, you get feedback earlier. For large datasets, this allows you to already check out the erroneous submissions while JPlag is still running.

@jplag/hiwi @jplag/maintainer any preferences?

2024-07-22 07:20 UTC, Kr0nox commented
I think printing them after would be better.
1) Then all errors are accumulated together and not split between multiple instances of the progress bar
2) It is easier to follow the process of the current taks, when you dont have to switch progress bars.
But that is just my opinion. Feel free to object

2024-07-22 07:23 UTC, Kr0nox commented
![grafik](https://github.com/user-attachments/assets/378e77dc-2e21-4106-af4d-a491de293fef)
There also seems to be an issue with printing. These two failed submission are exact copies of each other, but the reason is only printed for one of them

2024-07-30 07:13 UTC, Kr0nox commented
> There also seems to be an issue with printing. These two failed submission are exact copies of each other, but the reason is only printed for one of them

This seems to be fixed now

>Do we want the errors to be printed like they are in the screenshot or after a specific progress bar has run to 100%.
With the current way, a specific progress bar may be printed multiple times with different percentages.

@TwoOfTwelve Did you also change it to this behavior? Or was it the default in your PR anyways or is my dataset just small enough that the errors are printed so late?

2024-08-01 11:18 UTC, merged