Added token position tests for annotations
jplag/JPlag pull request #1960
Opened 2024-09-03 13:39 UTC by TwoOfTwelve

Added some token position tests for annotations. The tests currently fail, because I decided on different lengths than the java module currently reports.

The lengths I assume for these test:

-Annotation: from @ to end of annotation name
-Annotation type begin: from the first modifier to the end of the name
All other tokens lengths are the same as in the current implementation 

There are also some considerations for the module:

Most of the annotation token types seem to be unused. Maybe we should remove them?
I guess ANNO_M was supposed to be annotation members. They are currently extracted as Method tokens. Do we want to keep it like that?
Annotation arguments are currently not extracted at all. Do we want some tokens for that?

2024-10-31 12:40 UTC, uuqjz requested changes
Please move the comment

2024-10-31 12:40 UTC, uuqjz commented on languages/java/src/main/java/de/jplag/java/TokenGeneratingTreeScanner.java
> +            addToken(JavaTokenType.J_ANNO_T_BEGIN, start - 2 /* @ is final modifier for annotations */, (start - 2) + 11 + nameLength, semantics);
This inline comment look awful between two parameters

2024-11-06 15:30 UTC, tsaglam approved these changes
Looks good.

My initial thoughts on the open points:
> Most of the annotation token types seem to be unused. Maybe we should remove them?

Yes, we can do that, probably in a separate PR to also cover #1865.

> I guess ANNO_M was supposed to be annotation members. They are currently extracted as Method tokens. Do we want to keep it like that?

During the declaration of the annotation members in the annotation definition? There I would stick to method tokens.

> Annotation arguments are currently not extracted at all. Do we want some tokens for that?

We could actually do this. However, ideally, it would only be for mandatory ones. If we do it for optional ones, you can affect the tokens by removing the argument or adding an argument with the same value as the default.

Let me know what you guys think!

2024-11-21 12:35 UTC, tsaglam commented
@uuqjz ready from your side?

2024-12-03 09:00 UTC, uuqjz approved these changes
LGTM

2024-12-03 09:09 UTC, merged