Add ability to open old report viewers
jplag/JPlag pull request #2085
Opened 2024-11-30 12:24 UTC by Kr0nox

This PR adds the ability to open report viewers for older versions in local mode.

When a zip from a version that is not supported by the newest viewer gets uploaded, the user gets redirected to a seperate view that informs the user of this and offers them to open the viewer supports the report.

This PR currently only includes the report viewer that was published with version 5.1.0, which accepts reports dating back to version 4.2.0. Should a report viewer that accepts results from versions 4.0.0 and 4.1.0 also be included?

<details>
  <summary>View for opening old versions</summary>
	<img src="https://github.com/user-attachments/assets/2830615a-e78e-4059-adc2-0166a9f430fd" />

</details>

relates to #1190

2024-12-03 08:51 UTC, tsaglam commented
> I would not include all old versions of the viewer. I'd suggest that it only shows something like "Please use JPlag vX.Y" and then a user can download the resp. version of JPlag

I agree; I think until including 4.2.0 should be enough...

2025-01-23 09:41 UTC, tsaglam requested changes
Looks good! Just a few ideas regarding wording.

2025-01-23 09:41 UTC, tsaglam commented on cli/src/main/resources/v5/index.html
> +        >We're sorry but the JPlag Report Viewer does not work properly without JavaScript enabled.
```suggestion
        >We are sorry, but the JPlag Report Viewer does not work properly without JavaScript enabled.
```

2025-01-23 09:41 UTC, tsaglam commented on report-viewer/tests/e2e/OpenOldReport.spec.ts
> +    expect(bodyContent).toContain('Open old report viewer')
```suggestion
    const bodyContent = await page.locator('body').textContent()
    expect(bodyContent).toContain('You are trying to open a report created with an older version of JPlag')
    expect(bodyContent).toContain(oldVersion.version)
    expect(bodyContent).toContain('You can still view this report here:')
    expect(bodyContent).toContain('Open with old report viewer')
```

2025-01-23 09:41 UTC, tsaglam commented on report-viewer/src/views/OldVersionRedirectView.vue
> +        </div>
```suggestion
        <div class="space-y-2">
          <h3 class="text-2xl font-bold">
            You are trying to open a report created with an older version of JPlag
          </h3>
          <p class="text-xl">
            Your report was created with JPlag version {{ uploadedVersion.toString() }}. <br />
            The current version of JPlag is {{ reportViewerVersion.toString() }}. It supports reports starting from version {{ minimalReportVersion.toString() }}<br />
            You can still view the old report here:
          </p>
        </div>
```

2025-01-23 17:45 UTC, Kr0nox commented on report-viewer/tests/e2e/OpenOldReport.spec.ts
> +    expect(bodyContent).toContain('Open old report viewer')
@tsaglam You added the with in the last line of this suggestion in this test file, but not in the actual view. should I add it there?

2025-01-24 07:19 UTC, tsaglam commented on report-viewer/tests/e2e/OpenOldReport.spec.ts
> +    expect(bodyContent).toContain('Open old report viewer')
Yes, that would be great.

2025-01-24 07:54 UTC, merged