Enable Multiroot for Report Viewer
jplag/JPlag pull request #569
Opened 2022-08-05 16:23 UTC by nestabentum

This is still WIP but I wanted to share my approach already to receive feedback

This PR intends to fix two major issues (both noted in issue #354):

1. Submission names were concatenated to produce the comparison file name. When JPlag is run with multiple roots, the submission names contain backward slashes causing file creation to crash.
2. As Submission names were concatenated  duplicate names could easily be produced in the single source case ({`A, A-B, C, B-C}` would result in two `A-B-C` )

My approach to fixing this:

 * Differentiation between the submission name, submission id, and submission display name.
      * `Submission name` simply refers to Submission#name
      * `Submission id` is newly introduced and used only in the context of the report viewer creation. Generation of this id is the topic of another (our next 😄 ) discussion, but currently, it is the sanitized version of the submission name (File separator replaced by underscore). This submission id serves as an id for internal handling in the report viewer. 
      * `Display name` is the name of a submission to be displayed by the report viewer. The `overview.json` file contains a map <`submission id` -> `display name`> the report viewer will use to resolve the name for presentation purposes.
 * Two be able to abolish name concatenation of submission names for the comparison file name, I introduced a nested lookup table to the `overview.json`. It has the structure <`submission id `-> <<`submission id`> -><`comparison file name`>>>. With this data structure, there will be no duplicate comparison file names and additionally, the comparison file name can be chosen arbitrarily as the frontend will only have to execute two gets two receive the file name and will not have to rely on string concatenation.

Currently, the nested lookup table contains all submission ids in its first level, and in the second level, it contains each comparison for the corresponding submission id. This redundancy could be eliminated and actually halve the table's size but this is an optimization for later.
The UI isn't fully compatible with this approach yet, but will be with my next commits.

2022-08-09 21:46 UTC, dfuchss reviewed
Very minor comments :)

2022-08-09 21:46 UTC, dfuchss commented on jplag/src/main/java/de/jplag/reporting/jsonfactory/DirectoryCreator.java
> +            logger.error("Failed to create dir.");
If recovery is not possible. You should use exceptions

2022-08-09 21:46 UTC, dfuchss commented on jplag/src/test/java/de/jplag/reporting/reportobject/mapper/ComparisonReportWriterTest.java
> +    public void test() throws ExitException {
Maybe use a better name for the test

2022-08-12 14:02 UTC, sebinside approved these changes
I only had a quick look over the code, so there is a more in-depth review from @jplag/studdev required. But it tested the PR with two directories with 200 and 50 submissions, and everything worked fine.

Probably not related to this PR, but sometimes, the comparison viewer still breaks, but not predictable with the warning `Could not find comparison file. indes.js:43` and then with the error:
```
templateLoader.js?e847:50 
        
       Uncaught (in promise) TypeError: _ctx.isAnonymous is not a function
    at Proxy.render (templateLoader.js?e847:50:1)
    at renderComponentRoot (runtime-core.esm-bundler.js?d2dd:896:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js?d2dd:5580:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js?89dc:185:1)
    at instance.update (runtime-core.esm-bundler.js?d2dd:5694:1)
    at setupRenderEffect (runtime-core.esm-bundler.js?d2dd:5708:1)
    at mountComponent (runtime-core.esm-bundler.js?d2dd:5490:1)
    at processComponent (runtime-core.esm-bundler.js?d2dd:5448:1)
    at patch (runtime-core.esm-bundler.js?d2dd:5038:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js?d2dd:5660:1)
```

2022-08-15 13:51 UTC, tsaglam requested changes
Just a few minor things...

2022-08-15 13:51 UTC, tsaglam commented on jplag/src/main/java/de/jplag/reporting/jsonfactory/DirectoryCreator.java
> +public class DirectoryCreator {
JDoc

2022-08-15 13:51 UTC, tsaglam commented on jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
> +        if (submissionsPath == null)
Avoid if statements without curly braces.

2022-08-15 13:51 UTC, tsaglam commented on jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
> +        return directory;
```suggestion
        try {
            return createDirectory(submissionsPath.getPath(), submissionToIdFunction.apply(submission));
        } catch (IOException e) {
            logger.error("Could not create directory " + path + " for report viewer generation", e);
            return null;
        }
```

2022-08-15 13:51 UTC, tsaglam commented on jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
> +        return submissionsPath;
As above.

2022-08-15 13:51 UTC, tsaglam commented on jplag/src/main/java/de/jplag/reporting/reportobject/mapper/SubmissionNameToIdMapper.java
> +public class SubmissionNameToIdMapper {
JDoc

2022-08-15 13:51 UTC, tsaglam commented on jplag/src/main/java/de/jplag/reporting/reportobject/mapper/SubmissionNameToIdMapper.java
> +        return comparison.getName().replace(File.separator, "_");
Ideally `"_"` should be a constant.

2022-08-22 08:40 UTC, tsaglam approved these changes
Looks good! @nestabentum ready to merge from your end?

2022-08-22 13:43 UTC, nestabentum commented
@tsaglam this is good to go

2022-08-22 13:51 UTC, merged

2022-08-23 10:02 UTC, robinmaisch commented
Sorry, I'm late to the party, but I noticed that the `ComparisonReportWriterTest` writes test report files to `${baseDir}\jPlag` and does not remove them afterwards. I suggest that they are created in a special output directory and/or removed after the test.

2022-08-23 11:02 UTC, tsaglam commented
> 

Should be already fixed by #607