Parallel comparison file writing fix
jplag/JPlag pull request #659
Opened 2022-09-12 07:24 UTC by tsaglam

Concerns  #657:

- Synchronize comparison name generation to ensure uniquely identifying names
- Implement a more efficient comparison file name calculation that avoids repeatedly iterating over map values.

2022-09-12 13:18 UTC, dfuchss requested changes

2022-09-12 13:19 UTC, dfuchss commented on jplag/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
> +            fileNameCollisions.put(name, 1);
This would lead to no "synchronized" method

2022-09-13 12:09 UTC, dfuchss commented on jplag/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
> +    private final Map<String, AtomicInteger> fileNameCollisions = new HashMap<>();
ConcurrentHashMap is needed here :)

2022-09-13 12:12 UTC, tsaglam commented on jplag/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
> +    private final Map<String, AtomicInteger> fileNameCollisions = new HashMap<>();
Oops, I forgot to change that.

2022-09-13 12:14 UTC, dfuchss approved these changes

2022-09-13 12:32 UTC, merged