Fix/match display and reenable cluster
jplag/JPlag pull request #816
Opened 2022-11-23 20:23 UTC by cyfml

I fixed the bug: The ends of displayed matches are sometimes off by one and re-enable cluster. It is based on that file path problem is  resolved (last PR).
In addition, i added a test case to test cluster.

2022-11-24 13:06 UTC, sebinside commented
Just a reminder from the discussion: Please also fix that the starting line is off by one

2022-12-05 12:32 UTC, tsaglam requested changes
This PR contains new test resources but no new test case? They are probably from testing and can be removed, right?

2022-12-06 11:58 UTC, cyfml commented
> This PR contains new test resources but no new test case? They are probably from testing and can be removed, right?

Yes. After today's classes, i will take a look.

2022-12-09 16:12 UTC, sebinside reviewed
The code looks okay to me, the match display also seems to work correctly now.

However, we noticed a bug in the ReportGenerator (not your fault, this bug probably existed for a long time). Sometimes, the submission IDs in the array of the cluster's members are serialized as `null` which breaks everything. I will try to have a look at it next week. If would be good if you could also try to replicate this behavior. Currently, I don't know why this happens.

2022-12-09 16:12 UTC, sebinside commented on core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
> +                clusteringResultMapper.map(result)); // clusters (activated for now)
Please remove the `(activated for now)` as this information is no longer required

2022-12-12 09:38 UTC, sebinside commented
We found another bug in the report generation, it was fixed with #842. Please rebase your PR so that we can test it again, afterward, it can be merged.

2022-12-12 10:18 UTC, cyfml commented
@sebinside already done.

2022-12-12 10:30 UTC, tsaglam approved these changes

2022-12-12 10:35 UTC, sebinside approved these changes

2022-12-12 10:50 UTC, merged